### ISSUE TITLE
Glimesh.json not populated on startup

### ISSUE THREAD

**Issue by Sovak3441** [GlobalGamer2015/Glimesh-Chat-Bot#2]
When i try running the script for the first time, it does not populate the glimesh.json object ? So it does not seem to store the token from the initial request when first logging in.

**Comment by GlobalGamer2015** [comment]
Correct, I recommend using Postman to grab the tokens and everything then update the Glimesh.json file and then it will work as intended.

**Comment by GlobalGamer2015** [comment]
Updated readme on how to get the first time oauth codes.
